---
- name: Create EC2 instance for hosting Drupal and CiviCRM 
  hosts: localhost
  gather_facts: False

  vars:
      region: us-east-1
      instance_type: t2.micro
      ami: ami-059eeca93cf09eebd  # Ubuntu Server 16.04 LTS (HVM), SSD Volume Type
      keypair: boto_keypair # This is one of my keys that I already have in AWS
      security_group: BOTO-SecGroup
  
     - name: Add new instance to proper ansible group
       add_host: hostname=ec2-54-152-105-245.compute-1.amazonaws.com groupname=rafael-servers ansible_ssh_host=54.152.105.245 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/user/boto_keypair.pem
       with_items: ec2.tagged_instances

     - name: Wait for SSH to come up
       wait_for: host={{ item.public_ip }} port=22  search_regex=OpenSSH delay=210 timeout=420 state=started
       with_items: ec2.tagged_instances


- name: Configure EC2 instance
  hosts: rafael-servers
  become: Yes
  gather_facts: False
  tasks:
    - name: Update repo
      raw: apt-get update

    - name: install python2
      raw: sudo apt-get -y install python-minimal python-mysqldb
   
    - name: install Git
      raw: sudo apt-get -y install git

    - name: Create Site user
      user: 
        name: myuser
        password: $6$Zh3V6egoV$7m2XGdMaiKbrP/YF927y/cyA1kN9XfUbMzNRS1fRWzlv2pJAOeFXGSdSpUDgAKGaZ1JJidRLlJWY0CujRPkjv0
        shell: /bin/bash
        group: sudo

    - name: Allow SSH access with password
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication yes"
                  state=present

    - name: Restart SSH  
      service: name=ssh state=restarted
   

- include: packages-install.yml  
- include: drupal-setup.yml
- include: civicrm-setup.yml

#     - debug: var=ec2

