---
- name: Create EC2 instance for hosting Drupal and CiviCRM
  hosts: localhost
  gather_facts: False

  vars:
      region: us-east-1
      instance_type: t2.micro
      ami: ami-059eeca93cf09eebd  # Ubuntu Server 16.04 LTS (HVM), SSD Volume Type
      keypair: boto_keypair # This is one of my keys that I already have in AWS
      keypair_path: /home/user/boto_keypair.pem

  tasks:
     - name: create a security group
       ec2_group:
         name: DRUPAL_CIVICRM_SecGroup
         description: DRUPAL_CIVICRM_SecGroup

         region: "{{ region }}"
         rules:
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 443
             to_port: 443
             cidr_ip: 0.0.0.0/0
         rules_egress:
           - proto: all
             from_port: 0
             to_port: 65535
             cidr_ip: 0.0.0.0/0
       register: security_group

     - name: Create the ec2 instance
       ec2:
          group: DRUPAL_CIVICRM_SecGroup  # security group name
          instance_type: "{{ instance_type}}"
          image: "{{ ami }}"
          wait: true
          region: "{{ region }}"
          exact_count: 1
          #count: 1  # default
          count_tag:
             Name: ubuntu_16.4_instance
          instance_tags:
             Name: ubuntu_16.4_instance
          keypair: "{{ keypair }}"
       register: ec2

     - debug: var=ec2.tagged_instances


     - name: Add new instance to proper ansible group
       add_host: hostname={{ item.public_dns_name }} groupname=rafael-servers ansible_ssh_host={{ item.public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file="{{ keypair_path}}"
       with_items: '{{ ec2.tagged_instances }}'

     - name: Wait for port 22 - ssl connection
       wait_for: port=22 host={{ item.public_ip }} search_regex=OpenSSH delay=60 state=started
       with_items: '{{ ec2.tagged_instances }}'


- name: Configure EC2 instance
  hosts: rafael-servers
  become: Yes
  gather_facts: False
  tasks:
    - name: Update repo
      raw: apt-get update

    - name: install python2
      raw: sudo apt-get -y install python-minimal python-mysqldb

    - name: install Git
      raw: sudo apt-get -y install git

    - name: Create Site user
      user:
        name: myuser
        password: $6$Zh3V6egoV$7m2XGdMaiKbrP/YF927y/cyA1kN9XfUbMzNRS1fRWzlv2pJAOeFXGSdSpUDgAKGaZ1JJidRLlJWY0CujRPkjv0
        shell: /bin/bash
        group: sudo

    - name: Allow SSH access with password
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication yes"
                  state=present

    - name: Restart SSH
      service: name=ssh state=restarted


- include: packages-install.yml
- include: drupal-setup.yml
- include: civicrm-setup.yml
